---
interfaces:
  lo:
    description: spine2 loopback
    ipv4: 10.0.0.3/32
  eth1:
    description: spine2 x superspine1
    ipv4: 10.25.0.3/31
  eth2:
    description: spine2 x superspine2
    ipv4: 10.25.0.11/31
  eth3:
    description: spine2 x leaf1
    ipv4: 10.25.0.24/31
  eth4:
    description: spine2 x leaf2
    ipv4: 10.25.0.26/31
  eth5:
    description: spine2 x leaf3
    ipv4: 10.25.0.28/31
  eth6:
    description: spine2 x leaf4
    ipv4: 10.25.0.30/31
bgp:
  neighbors:
  - name: superspine1
    remote:
      addr: 10.25.0.2
      asn: 64512
  - name: superspine2
    remote:
      addr: 10.25.0.10
      asn: 64512
  - name: leaf1
    remote:
      addr: 10.25.0.25
      asn: 64514
  - name: leaf2
    remote:
      addr: 10.25.0.27
      asn: 64514
  - name: leaf3
    remote:
      addr: 10.25.0.29
      asn: 64514
  - name: leaf4
    remote:
      addr: 10.25.0.31
      asn: 64514
