---
interfaces:
  lo:
    description: spine1 loopback
    ipv4: 10.0.0.2/32
  eth1:
    description: spine1 x superspine1
    ipv4: 10.25.0.1/31
  eth2:
    description: spine1 x superspine2
    ipv4: 10.25.0.9/31
  eth3:
    description: spine1 x leaf1
    ipv4: 10.25.0.16/31
  eth4:
    description: spine1 x leaf2
    ipv4: 10.25.0.18/31
  eth5:
    description: spine1 x leaf3
    ipv4: 10.25.0.20/31
  eth6:
    description: spine1 x leaf4
    ipv4: 10.25.0.22/31
bgp:
  neighbors:
  - name: superspine1
    remote:
      addr: 10.25.0.0
      asn: 64512
  - name: superspine2
    remote:
      addr: 10.25.0.8
      asn: 64512
  - name: leaf1
    remote:
      addr: 10.25.0.17
      asn: 64514
  - name: leaf2
    remote:
      addr: 10.25.0.19
      asn: 64514
  - name: leaf3
    remote:
      addr: 10.25.0.21
      asn: 64514
  - name: leaf4
    remote:
      addr: 10.25.0.23
      asn: 64514
