---
interfaces:
  lo:
    description: superspine1 loopback
    ipv4: 10.0.0.0/32
  eth1:
    description: superspine1 x spine1
    ipv4: 10.25.0.0/31
  eth2:
    description: superspine1 x spine2
    ipv4: 10.25.0.2/31
  eth3:
    description: superspine1 x spine3
    ipv4: 10.25.0.4/31
  eth4:
    description: superspine1 x spine4
    ipv4: 10.25.0.6/31
bgp:
  neighbors:
  - name: spine1
    remote:
      addr: 10.25.0.1
      asn: 64513
  - name: spine2
    remote:
      addr: 10.25.0.3
      asn: 64513
  - name: spine3
    remote:
      addr: 10.25.0.5
      asn: 64513
  - name: spine4
    remote:
      addr: 10.25.0.7
      asn: 64513
