---
interfaces:
  lo:
    description: spine4 loopback
    ipv4: 10.0.0.5/32
  eth1:
    description: spine4 x superspine1
    ipv4: 10.25.0.7/31
  eth2:
    description: spine4 x superspine2
    ipv4: 10.25.0.15/31
  eth3:
    description: spine4 x leaf1
    ipv4: 10.25.0.40/31
  eth4:
    description: spine4 x leaf2
    ipv4: 10.25.0.42/31
  eth5:
    description: spine4 x leaf3
    ipv4: 10.25.0.44/31
  eth6:
    description: spine4 x leaf4
    ipv4: 10.25.0.46/31
bgp:
  neighbors:
  - name: superspine1
    remote:
      addr: 10.25.0.6
      asn: 64512
  - name: superspine2
    remote:
      addr: 10.25.0.14
      asn: 64512
  - name: leaf1
    remote:
      addr: 10.25.0.41
      asn: 64514
  - name: leaf2
    remote:
      addr: 10.25.0.43
      asn: 64514
  - name: leaf3
    remote:
      addr: 10.25.0.45
      asn: 64514
  - name: leaf4
    remote:
      addr: 10.25.0.47
      asn: 64514
